### ISSUE TITLE
README.md enhancement

### ISSUE THREAD

**Issue by techonerd** [techonerd/stock-assist#12]
@Casper-Morning-Star Look for a way how we gonna add the issues and pull request stats in our README.md 

If you need any help, feel free to ask around.

@kido-kit-kat guide him.

**Comment by Casper-Morning-Star** [comment]
[![GitHub issues](https://img.shields.io/github/issues-raw/techonerd/stock-assist?color=red)](https://github.com/techonerd/stock-assist/issues?q=is%3Aopen+is%3Aissue)
[![GitHub closed issues](https://img.shields.io/github/issues-closed-raw/techonerd/stock-assist)](https://github.com/techonerd/stock-assist/issues?q=is%3Aissue+is%3Aclosed)
[![GitHub pull requests](https://img.shields.io/github/issues-pr-raw/techonerd/stock-assist?color=brightgreen)](https://github.com/techonerd/stock-assist/pulls?q=is%3Aopen+is%3Apr)
[![GitHub closed pull requests](https://img.shields.io/github/issues-pr-closed-raw/techonerd/stock-assist?color=green)](https://github.com/techonerd/stock-assist/pulls?q=is%3Apr+is%3Aclosed)


This is the final outcome what we have achieved. Please provide your inputs @kido-kit-kat .

**Comment by kido-kit-kat** [comment]
Looks fine to me. But will it be always accurate, like in real-time? How are we going to achieve that? @techonerd

**Comment by techonerd** [comment]
That has been taken care @kido-kit-kat. Good work @Casper-Morning-Star.
